export type Priority = 'Severe' | 'High' | 'Medium';
export type TaskStatus = 'backlog' | 'picked' | 'in-progress' | 'blocked' | 'done' | 'skipped';

export type AuditTask = {
  id: string;
  title: string;
  summary: string;
  action: string;
  risk: string;
  priority: Priority;
  area: string;
  files: string[];
  status: TaskStatus;
  latest?: boolean;
};

const riskOverrides: Record<string, string> = {
  'SEC-01': 'This is Severe because inconsistent authentication gates can create a direct path to full card details, exports, or settings without the intended user verification. A single missed call site defeats otherwise strong protection.',
  'SEC-02': 'This is Severe because an unlocked vault that survives backgrounding can be reopened by anyone who gains brief physical access to the device, exposing all protected records without another biometric or passcode challenge.',
  'SEC-03': 'This is Severe because even a short first-frame race can render decrypted or identifiable content before the lock decision completes. Screen capture, app-switcher snapshots, or observation can make that transient disclosure permanent.',
  'PRV-01': 'This is Severe because screenshots and recordings create durable, unencrypted copies of PAN, expiry, identity, and other protected fields outside CardVault’s encryption and deletion controls.',
  'PRV-02': 'This is Severe because operating-system task snapshots can expose the last protected screen without reopening the app or authenticating, bypassing the vault boundary at a system-controlled surface.',
  'BKP-01': 'This is Severe because a failed import can overwrite or mix trusted vault state with partially validated data. The result can be irreversible loss, broken encryption references, or records whose files and metadata no longer agree.',
  'BKP-02': 'This is Severe because attacker-controlled archive identifiers can become filesystem paths. Without canonical containment checks, a crafted backup may overwrite files outside the import directory and compromise app data or configuration.',
  'BKP-03': 'This is Severe because a small malicious archive can expand into excessive files, bytes, or image pixels, exhausting memory or storage before validation and repeatedly crashing the app during import.',
  'CMP-01': 'This is Severe because retaining a CVV creates high-value authentication data that should not be stored after authorization. A vault compromise would expose everything needed for card-not-present fraud and create serious compliance risk.',
  'OCR-01': 'This is High because an oversized or malformed image can force a large native bitmap allocation before Flutter can recover, causing process termination and a repeatable denial of service during scanning or import.',
  'MEM-04': 'This is High because repeated full-resolution decodes multiply peak heap and GPU memory during common card transitions. On mid-range devices this can cause visible stalls, memory pressure, or an out-of-memory crash.',
  'MEM-05': 'This is High because unreleased native scanner bitmaps are outside normal Dart heap visibility and can accumulate across scans until the process is killed, even when Flutter memory appears stable.',
  'MEM-06': 'This is High because retaining source-resolution artwork for tiny previews creates avoidable persistent memory growth across icon lists and settings screens, increasing crash risk on low-memory devices.',
  'MEM-07': 'This is High because constructing an archive and all of its records and images in memory can make legitimate large vaults impossible to back up or restore and makes resource-exhaustion attacks easier.',
  'IOS-02': 'This is High because the missing native bridge leaves a core scan path unavailable or inconsistent on an entire supported platform, forcing fallback behavior and creating platform-specific data-quality failures.',
  'CLP-01': 'This is High because the system clipboard is readable by clipboard history, keyboards, device-management tools, and other apps under some conditions. Copied PAN, expiry, or CVV can outlive the authenticated session.',
  'NFC-01': 'This is High because raw APDU traffic can contain payment identifiers and protocol data. Production logs may be collected, backed up, or shared with support, moving sensitive information outside the encrypted vault.',
  'AI-01': 'This is High because retained OCR images, prompts, responses, or extracted fields can duplicate complete card data in diagnostic storage with weaker access controls and a longer lifetime than the source record.',
  'AI-02': 'This is High because processing card data with a remote provider without informed opt-in crosses a trust boundary the user may not expect and can create privacy, contractual, and regulatory exposure.',
  'CRY-01': 'This is High because permissive Keychain accessibility can make encryption keys available in states or backups beyond the intended device-only, post-unlock boundary, weakening the protection of every encrypted record.',
  'CRY-02': 'This is High because stolen backup files can be attacked offline without rate limits. A weak or unversioned password KDF makes password guessing materially cheaper and can expose the complete vault.',
  'STO-02': 'This is High because plaintext metadata can reveal cardholder identity, issuer, last digits, notes, and account relationships even when the primary encrypted payload remains intact.',
  'STO-03': 'This is High because stored card and background images may visibly contain names, numbers, or account branding. Plain files bypass database encryption and can leak through backups, file tools, or forensic recovery.',
  'FIL-01': 'This is High because broad or legacy storage access expands the number of apps and system surfaces that may observe exported or temporary vault files and can leave data behind after permissions change.',
  'AND-01': 'This is High because any accidental HTTP endpoint or redirected request could transmit credentials or card-derived data without transport encryption, allowing interception or modification on an untrusted network.',
  'DATA-01': 'This is High because stale plaintext caches can continue serving decrypted values after the UI is locked. That turns a presentation lock into a partial control while sensitive data remains accessible in process memory.',
  'PERF-07': 'This is High because starting asynchronous reads or decryptions from build can create repeated work loops, stale result races, and frame churn on a core protected screen rather than a rare background path.',
  'PERF-08': 'This is High because eagerly decrypting the whole collection increases startup latency and the amount of plaintext resident in memory at once, combining performance degradation with unnecessary sensitive-data exposure.',
  'REL-02': 'This is High because an interrupted model installation can leave a corrupt file that is mistaken for a valid dependency, disabling OCR on every subsequent launch until storage is repaired or the app is reinstalled.',
  'DEP-04': 'This is High because a security-sensitive native scanner fork can silently diverge from upstream fixes. Local patches, native code, camera access, and ML processing make delayed maintenance especially costly.',
  'DEP-05': 'This is High because the native inference runtime materially affects APK size and carries its own native-memory and vulnerability surface; an unsupported version cannot be mitigated by Dart-level controls.',
  'APK-08': 'This is High because the scanner contributes roughly 15.5 MB compressed to every relevant APK, materially affecting download, update, and install conversion even for users who never use scanning.',
};

const mediumRiskByArea: Record<string, string> = {
  Memory: 'This is Medium because it can produce gradual memory growth, jank, or device-specific crashes, but the current evidence does not show a direct data compromise or deterministic failure for every user.',
  Performance: 'This is Medium because it degrades responsiveness and scalability under load, while core data correctness and security are not immediately lost in the observed path.',
  Privacy: 'This is Medium because sensitive information may be exposed only through a bounded local surface or an additional device/accessibility condition, rather than through a direct remote disclosure path.',
  'APK Size': 'This is Medium because it increases download, installation, and update cost and can reduce adoption, but it does not by itself compromise data or break a critical workflow.',
  Build: 'This is Medium because weak release controls make regressions and configuration mistakes more likely, but exploitation or user impact requires a later faulty build or release event.',
  Platform: 'This is Medium because it affects platform compliance or resilience for a subset of users and release conditions rather than exposing the whole vault immediately.',
  Storage: 'This is Medium because lifecycle or organization gaps can leave orphaned data and complicate cleanup, but the finding is not currently a direct arbitrary-read or arbitrary-write primitive.',
  Reliability: 'This is Medium because it can cause recoverable failures or rare state corruption during exceptional conditions, with no confirmed universal loss path in normal operation.',
  Cleanup: 'This is Medium because dead or duplicated code increases maintenance and regression risk over time, but removing it is not an emergency production security fix.',
  Refactoring: 'This is Medium because tightly coupled code increases the chance and cost of future defects; the architectural debt is material but is not itself a confirmed exploit.',
  Testing: 'This is Medium because the missing coverage reduces confidence and allows regressions to escape, but it is evidence of verification risk rather than proof that the associated production path is already broken.',
  Dependencies: 'This is Medium because outdated or unnecessary packages expand maintenance and supply-chain exposure, while no directly exploitable production vulnerability is currently attributed to this task.',
  'CI/CD': 'This is Medium because missing automated gates allow future defects into release branches, but user impact depends on a subsequent change passing review unchecked.',
  Security: 'This is Medium because exploitation requires additional local access, diagnostic access, or a secondary failure; the exposure is meaningful but not a direct vault-wide bypass.',
  Accessibility: 'This is Medium because inaccessible controls can block important workflows for affected users, while the issue does not directly expose or corrupt stored data.',
  Documentation: 'This is Medium because undocumented trust boundaries make future security mistakes more likely and incident response slower, but documentation alone is not a present exploit.',
  Operations: 'This is Medium because unclear ownership and response timelines increase the duration of future exposure, while impact depends on another vulnerability first being discovered.',
  UI: 'This is Medium because the defect harms visual trust and usability during a common interaction but does not alter protected values or storage integrity.',
};

function riskFor(id: string, priority: Priority, area: string, status: TaskStatus): string {
  if (riskOverrides[id]) return riskOverrides[id];
  const base = mediumRiskByArea[area] ?? `This is ${priority} because it creates meaningful engineering and user risk, but no immediate vault-wide compromise or irreversible data-loss path has been confirmed.`;
  return status === 'done' ? `${base} The recorded remediation is complete; retain regression coverage so the risk does not return.` : base;
}

const fileOverrides: Record<string, string[]> = {
  'SEC-01': ['lib/services/auth_service.dart', 'lib/services/security_service.dart', 'lib/providers/app_lock_provider.dart', 'lib/main.dart'],
  'SEC-02': ['lib/providers/app_lock_provider.dart', 'lib/services/auth_service.dart', 'lib/main.dart'],
  'SEC-03': ['lib/main.dart', 'lib/providers/app_lock_provider.dart', 'lib/services/security_service.dart'],
  'PRV-01': ['android/app/src/main/kotlin/com/cardswallet/cards_wallet/MainActivity.kt', 'ios/Runner/AppDelegate.swift', 'lib/screens/card_detail_screen.dart'],
  'PRV-02': ['lib/providers/app_lock_provider.dart', 'android/app/src/main/kotlin/com/cardswallet/cards_wallet/MainActivity.kt', 'ios/Runner/AppDelegate.swift'],
  'PRV-03': ['lib/screens/card_detail_screen.dart', 'lib/widgets/wallet_card_face.dart', 'lib/widgets/wallet_card.dart'],
  'BKP-01': ['lib/services/secure_card_storage.dart', 'lib/services/backup_crypto.dart', 'lib/widgets/backup_password_dialog.dart'],
  'BKP-02': ['lib/services/secure_card_storage.dart', 'lib/models/card_data.dart', 'test/backup_bundle_roundtrip_test.dart'],
  'BKP-03': ['lib/services/secure_card_storage.dart', 'lib/services/backup_crypto.dart', 'test/backup_bundle_roundtrip_test.dart'],
  'CMP-01': ['lib/models/card_data.dart', 'lib/screens/card_edit_screen.dart', 'lib/screens/card_detail_screen.dart', 'lib/services/secure_card_storage.dart'],
  'OCR-01': ['android/app/src/main/kotlin/com/cardswallet/cards_wallet/ocr/CardTextOcrHandler.kt', 'lib/services/ocr_service.dart', 'lib/utils/image_utils.dart'],
  'OCR-02': ['lib/services/ocr_service.dart', 'lib/services/card_text_ocr_service.dart', 'lib/screens/card_camera_screen.dart'],
  'OCR-03': ['lib/services/ocr_service.dart', 'lib/utils/image_utils.dart', 'lib/utils/image_crop_helper.dart'],
  'MEM-01': ['lib/screens/card_camera_screen.dart', 'lib/screens/card_detail_screen.dart', 'lib/screens/saved_cards_screen.dart', 'lib/providers/camera_provider.dart'],
  'MEM-02': ['lib/services/secure_card_storage.dart', 'lib/services/card_background_storage.dart', 'lib/screens/saved_cards_screen.dart'],
  'MEM-04': ['lib/utils/image_utils.dart', 'lib/widgets/card_background_surface.dart', 'lib/widgets/wallet_card.dart'],
  'MEM-05': ['android/stripe-cardscan-local/stripecardscan/src/main/java/com/stripe/android/stripecardscan/framework/image/MLImage.kt', 'android/stripe-cardscan-local/stripecardscan/src/main/java/com/stripe/android/stripecardscan/cardscan/CardScanActivity.kt', 'android/app/src/main/kotlin/com/cardswallet/cards_wallet/cardscan/CardScanHandler.kt'],
  'MEM-06': ['lib/providers/app_icon_provider.dart', 'lib/widgets/app_icon_artwork.dart', 'lib/models/app_icon_option.dart'],
  'MEM-07': ['lib/services/secure_card_storage.dart', 'lib/services/backup_crypto.dart', 'lib/services/card_attachment_storage.dart'],
  'IOS-02': ['ios/Runner/AppDelegate.swift', 'lib/services/ocr_service.dart', 'lib/services/card_text_ocr_service.dart'],
  'IOS-03': ['ios/Runner/PrivacyInfo.xcprivacy (new)', 'ios/Runner/Info.plist', 'ios/Podfile.lock'],
  'IOS-04': ['ios/Runner/AppDelegate.swift', 'lib/services/card_attachment_storage.dart', 'lib/services/card_background_storage.dart'],
  'CLP-01': ['lib/screens/card_detail_screen.dart', 'lib/services/auth_service.dart'],
  'NFC-01': ['lib/services/nfc_service.dart', 'lib/services/apdu_commands.dart', 'lib/providers/nfc_provider.dart', 'lib/screens/nfc_scan_screen.dart'],
  'AI-01': ['lib/services/ai_scan_log_service.dart', 'lib/screens/ai_scan_logs_screen.dart', 'lib/services/ai_card_scan_service.dart'],
  'AI-02': ['lib/services/ai_scan_settings_service.dart', 'lib/screens/ai_scan_settings_screen.dart', 'lib/services/ai_card_scan_service.dart'],
  'CRY-01': ['lib/services/encryption_service.dart', 'lib/services/security_service.dart', 'ios/Runner/AppDelegate.swift'],
  'CRY-02': ['lib/services/backup_crypto.dart', 'lib/services/secure_card_storage.dart', 'lib/widgets/backup_password_dialog.dart'],
  'STO-01': ['lib/services/secure_card_storage.dart', 'lib/services/card_attachment_storage.dart', 'lib/services/card_background_storage.dart', 'lib/services/card_group_storage.dart'],
  'STO-02': ['lib/models/card_data.dart', 'lib/services/secure_card_storage.dart', 'lib/services/encryption_service.dart'],
  'STO-03': ['lib/services/card_background_storage.dart', 'lib/services/card_attachment_storage.dart', 'lib/services/encryption_service.dart'],
  'FIL-01': ['lib/services/secure_card_storage.dart', 'lib/services/card_attachment_storage.dart', 'android/app/src/main/AndroidManifest.xml'],
  'FIL-02': ['lib/services/card_attachment_storage.dart', 'lib/services/card_background_storage.dart', 'lib/services/secure_card_storage.dart'],
  'FIL-03': ['lib/services/secure_card_storage.dart', 'lib/services/camera_service.dart', 'lib/services/card_attachment_storage.dart'],
  'AND-01': ['android/app/src/main/AndroidManifest.xml', 'android/app/src/main/res/xml/network_security_config.xml (new)'],
  'AND-02': ['android/app/src/main/AndroidManifest.xml', 'android/stripe-cardscan-local/stripecardscan/src/main/AndroidManifest.xml'],
  'DATA-01': ['lib/models/card_data.dart', 'lib/services/secure_card_storage.dart', 'lib/screens/saved_cards_screen.dart', 'lib/screens/card_detail_screen.dart'],
  'PERF-07': ['lib/screens/card_detail_screen.dart', 'lib/widgets/card_background_surface.dart', 'lib/widgets/wallet_card_face.dart'],
  'PERF-08': ['lib/screens/saved_cards_screen.dart', 'lib/widgets/infinite_card_deck.dart', 'lib/widgets/card_tiles_grid.dart', 'lib/widgets/stacked_card_grid.dart'],
  'REL-02': ['android/app/src/main/kotlin/com/cardswallet/cards_wallet/ocr/CardTextOcrHandler.kt', 'android/app/src/main/assets/tessdata/eng.traineddata'],
  'DEP-04': ['android/settings.gradle', 'android/stripe-cardscan-local/stripecardscan/build.gradle', 'android/stripe-cardscan-local/README.md'],
  'DEP-05': ['android/stripe-cardscan-local/ml-core-base/build.gradle', 'android/stripe-cardscan-local/ml-core-cardscan/build.gradle', 'android/stripe-cardscan-local/stripecardscan/build.gradle'],
  'APK-08': ['android/stripe-cardscan-local/stripecardscan/build.gradle', 'android/stripe-cardscan-local/ml-core-base/build.gradle', 'android/stripe-cardscan-local/ml-core-cardscan/build.gradle'],
  'APK-05': ['pubspec.yaml', 'assets/banks-logo-large/', 'assets/banks-logo-small/', 'assets/card_backgrounds/'],
  'APK-06': ['pubspec.yaml', 'assets/', 'lib/data/banks.dart', 'lib/data/card_designs.dart'],
  'APK-07': ['pubspec.yaml', 'assets/fonts/', 'lib/theme/app_typography.dart'],
  'APK-09': ['android/settings.gradle', 'android/app/build.gradle', 'android/stripe-cardscan-local/'],
  'APK-10': ['android/app/build.gradle', 'android/gradle.properties', '.github/workflows/android-release.yml (new)'],
  'BLD-01': ['android/app/build.gradle', 'android/gradle.properties', 'ios/Runner.xcodeproj/project.pbxproj'],
  'BLD-02': ['lib/main.dart', 'android/app/build.gradle', 'ios/Flutter/'],
  'BLD-03': ['pubspec.yaml', '.github/workflows/release.yml (new)', 'android/app/build.gradle'],
  'BLD-04': ['android/app/build.gradle', '.github/workflows/apk-size.yml (new)', 'docs/release-size-budget.md (new)'],
  'MED-01': ['lib/utils/image_utils.dart', 'lib/services/card_background_storage.dart', 'lib/services/card_attachment_storage.dart'],
  'MED-02': ['lib/utils/image_utils.dart', 'lib/services/card_attachment_storage.dart', 'lib/services/card_background_storage.dart'],
  'REL-01': ['lib/utils/debug_logger.dart', 'lib/services/secure_card_storage.dart', 'lib/services/ocr_service.dart'],
  'REL-03': ['lib/services/secure_card_storage.dart', 'lib/models/card_data.dart', 'test/secure_card_storage_test.dart'],
  'CLN-01': ['lib/', 'analysis_options.yaml', 'test/'],
  'CLN-02': ['android/stripe-cardscan-local/', 'android/settings.gradle', 'android/app/build.gradle'],
  'CLN-03': ['pubspec.yaml', '.gitignore', 'assets/'],
  'REF-01': ['lib/screens/saved_cards_screen.dart', 'lib/screens/card_detail_screen.dart', 'lib/screens/card_edit_screen.dart'],
  'REF-02': ['lib/models/card_data.dart', 'lib/services/secure_card_storage.dart', 'lib/services/encryption_service.dart'],
  'REF-03': ['lib/utils/card_formatter.dart', 'lib/utils/card_network_utils.dart', 'lib/widgets/wallet_card_face.dart'],
  'REF-04': ['lib/main.dart', 'lib/providers/app_lock_provider.dart', 'lib/services/auth_service.dart'],
  'REF-05': ['lib/providers/', 'lib/screens/saved_cards_screen.dart', 'lib/screens/card_detail_screen.dart'],
  'REF-06': ['lib/services/card_background_storage.dart', 'lib/services/card_attachment_storage.dart', 'lib/utils/image_utils.dart'],
  'REF-07': ['lib/services/ocr_service.dart', 'android/app/src/main/kotlin/com/cardswallet/cards_wallet/MainActivity.kt', 'ios/Runner/AppDelegate.swift'],
  'REF-08': ['lib/theme/app_motion.dart', 'lib/theme/app_spacing.dart', 'lib/utils/image_utils.dart'],
  'PERF-01': ['test/', 'integration_test/performance_test.dart (new)', 'lib/main.dart'],
  'PERF-02': ['lib/screens/saved_cards_screen.dart', 'lib/providers/card_view_provider.dart', 'lib/providers/profile_provider.dart'],
  'PERF-03': ['lib/screens/saved_cards_screen.dart', 'lib/providers/card_view_provider.dart', 'lib/utils/card_network_utils.dart'],
  'PERF-04': ['lib/widgets/infinite_card_deck.dart', 'lib/widgets/card_tiles_grid.dart', 'lib/widgets/stacked_card_grid.dart'],
  'PERF-05': ['lib/services/encryption_service.dart', 'lib/services/secure_card_storage.dart', 'lib/models/card_data.dart'],
  'PERF-06': ['lib/widgets/wallet_card_hero.dart', 'lib/widgets/infinite_card_deck.dart', 'lib/theme/app_motion.dart'],
  'TST-01': ['test/widget_test.dart', 'test/card_detail_screen_test.dart', 'test/app_lock_lifecycle_test.dart (new)'],
  'TST-02': ['test/backup_bundle_roundtrip_test.dart', 'lib/services/secure_card_storage.dart', 'test/fixtures/malicious_backups/ (new)'],
  'TST-03': ['android/app/src/test/ (new)', 'android/app/src/main/kotlin/com/cardswallet/cards_wallet/ocr/CardTextOcrHandler.kt', 'android/app/src/main/kotlin/com/cardswallet/cards_wallet/cardscan/CardScanHandler.kt'],
  'TST-04': ['test/wallet_card_hero_test.dart', 'test/card_tiles_grid_test.dart', 'test/goldens/ (new)'],
  'TST-05': ['test/', 'pubspec.yaml', 'coverage/lcov.info (generated)'],
  'TST-06': ['test/secure_card_storage_test.dart', 'test/backup_bundle_roundtrip_test.dart', 'test/fixtures/migrations/ (new)'],
  'TST-07': ['integration_test/memory_regression_test.dart (new)', 'lib/screens/card_camera_screen.dart', 'lib/screens/card_detail_screen.dart'],
  'TST-08': ['test/card_detail_screen_test.dart', 'test/saved_cards_accessibility_test.dart (new)', 'test/widget_test.dart'],
  'DEP-01': ['pubspec.yaml', 'pubspec.lock', 'lib/'],
  'DEP-02': ['pubspec.yaml', 'pubspec.lock', '.github/dependabot.yml (new)'],
  'DEP-03': ['pubspec.lock', 'android/app/build.gradle', 'tool/generate_sbom.dart (new)'],
  'CI-01': ['.github/workflows/quality-gate.yml (new)', 'analysis_options.yaml', 'pubspec.yaml'],
  'ERR-01': ['lib/utils/debug_logger.dart', 'lib/services/ai_scan_log_service.dart', 'lib/screens/card_detail_screen.dart'],
  'A11Y-01': ['lib/screens/card_detail_screen.dart', 'lib/screens/saved_cards_screen.dart', 'lib/widgets/wallet_card_face.dart'],
  'DOC-01': ['README.md', 'docs/security-architecture.md (new)', 'docs/threat-model.md (new)'],
  'OPS-01': ['SECURITY.md (new)', '.github/SECURITY.md (new)', '.github/workflows/'],
  'UI-01': ['lib/widgets/wallet_card_hero.dart', 'lib/widgets/infinite_card_deck.dart', 'lib/screens/card_detail_screen.dart'],
};

function filesFor(id: string, area: string): string[] {
  if (fileOverrides[id]) return fileOverrides[id];
  if (id.startsWith('APK-')) return ['pubspec.yaml', 'android/app/build.gradle', 'assets/'];
  if (id.startsWith('BLD-')) return ['android/app/build.gradle', 'android/gradle.properties', 'pubspec.yaml'];
  if (id.startsWith('TST-')) return ['test/', 'pubspec.yaml'];
  if (id.startsWith('DEP-')) return ['pubspec.yaml', 'pubspec.lock', 'android/app/build.gradle'];
  if (id.startsWith('PERF-')) return ['lib/screens/saved_cards_screen.dart', 'lib/screens/card_detail_screen.dart', 'lib/widgets/wallet_card.dart'];
  if (area === 'CI/CD') return ['.github/workflows/ (new)', 'analysis_options.yaml', 'pubspec.yaml'];
  return ['lib/', 'test/'];
}

const task = (
  id: string,
  title: string,
  priority: Priority,
  area: string,
  summary: string,
  action: string,
  status: TaskStatus = 'backlog',
  latest = false,
): AuditTask => ({ id, title, priority, area, summary, action, risk: riskFor(id, priority, area, status), files: filesFor(id, area), status, latest });

export const auditTasks: AuditTask[] = [
  task('SEC-01', 'Centralize authentication decisions', 'Severe', 'Security', 'Authentication checks are distributed across screens and services, which makes bypasses and inconsistent policy more likely.', 'Introduce a single authentication coordinator and route every sensitive read, reveal, export, and settings change through it.', 'backlog', true),
  task('SEC-02', 'Harden the authentication lifecycle', 'Severe', 'Security', 'The unlocked state can survive lifecycle transitions longer than intended.', 'Lock on background, enforce a short configurable timeout, and cover pause/resume plus biometric cancellation with tests.', 'backlog', true),
  task('SEC-03', 'Remove the startup lock race', 'Severe', 'Security', 'App initialization and lock-screen routing can race, briefly exposing protected UI.', 'Gate the first protected frame behind completed secure-storage and authentication initialization.', 'backlog', true),
  task('PRV-01', 'Block screenshots on sensitive screens', 'Severe', 'Privacy', 'Card details can be captured by screenshots or screen recording on Android.', 'Enable FLAG_SECURE while protected routes are visible and add an equivalent iOS capture policy.', 'backlog', true),
  task('PRV-02', 'Protect app-switcher previews', 'Severe', 'Privacy', 'Sensitive content may remain visible in recent-app snapshots.', 'Overlay or blur protected content before backgrounding and validate both Android and iOS task switchers.', 'backlog', true),
  task('BKP-01', 'Make backup imports transactional', 'Severe', 'Backup', 'A partially failed import can leave mixed or corrupted state.', 'Validate into a staging area, commit atomically, and roll back all files and records on failure.', 'backlog', true),
  task('BKP-02', 'Prevent backup path traversal', 'Severe', 'Backup', 'Imported card IDs can influence output paths and may escape the intended storage directory.', 'Reject unsafe IDs, canonicalize every destination, and prove it remains under the import root before writing.', 'backlog', true),
  task('BKP-03', 'Enforce backup resource limits', 'Severe', 'Backup', 'Untrusted archives have no strict entry-count, decompression-size, or image-dimension budget.', 'Set compressed/uncompressed size, file count, nesting, and image pixel limits before extraction or decode.', 'backlog', true),
  task('CMP-01', 'Reassess CVV persistence', 'Severe', 'Compliance', 'Persisting card security codes creates disproportionate security and compliance risk.', 'Remove stored CVV support, migrate existing values away, and document the product decision.', 'backlog', true),

  task('OCR-01', 'Bound native bitmap decoding', 'High', 'Memory', 'Native OCR can decode large camera images without a safe pixel budget, creating OOM risk.', 'Read bounds first, downsample before allocation, and reject images above the supported dimensions.', 'backlog', true),
  task('MEM-04', 'Eliminate repeated full-size image decodes', 'High', 'Memory', 'Card views repeatedly decode original images for display and animation.', 'Cache correctly sized derivatives and request decode dimensions that match the rendered widget.', 'backlog', true),
  task('MEM-05', 'Recycle scanner bitmaps deterministically', 'High', 'Memory', 'Native scanner bitmaps can outlive a scan attempt and increase peak memory.', 'Close or recycle every intermediate bitmap in finally blocks and validate with repeated-scan profiling.', 'backlog', true),
  task('MEM-06', 'Generate bounded icon previews', 'High', 'Memory', 'Brand/icon previews may retain oversized source images for small UI targets.', 'Create small cached thumbnails during ingestion and render those in lists and pickers.', 'backlog', true),
  task('MEM-07', 'Stream backup creation and restore', 'High', 'Memory', 'Backup flows can hold archives, records, and images in memory at the same time.', 'Stream entries to disk, process incrementally, and avoid whole-archive byte arrays.', 'backlog', true),
  task('IOS-02', 'Implement the missing iOS Vision OCR bridge', 'High', 'Platform', 'The iOS path does not provide parity with the native OCR capability used on Android.', 'Add the Vision channel implementation, cancellation, error mapping, and device tests.', 'backlog', true),
  task('CLP-01', 'Protect clipboard operations', 'High', 'Privacy', 'Copied card data can remain readable by other apps and clipboard history.', 'Use explicit user actions, show warnings, auto-clear where supported, and never copy CVV.', 'backlog', true),
  task('NFC-01', 'Remove raw APDU logging', 'High', 'Security', 'Low-level NFC messages may expose payment data in logs.', 'Delete payload logging, redact identifiers, and make diagnostic logs opt-in and non-production.', 'backlog', true),
  task('AI-01', 'Minimize AI diagnostic retention', 'High', 'Privacy', 'OCR/AI diagnostics can preserve sensitive images or extracted card text.', 'Disable retention by default, redact structured fields, bound lifetime, and provide an explicit purge action.', 'backlog', true),
  task('AI-02', 'Add explicit AI-processing consent', 'High', 'Privacy', 'Users may not understand when card data leaves the device for processing.', 'Add informed opt-in before upload, disclose provider and retention, and keep an offline path available.', 'backlog', true),
  task('CRY-01', 'Tighten iOS key accessibility', 'High', 'Crypto', 'Keychain accessibility should prevent secrets from being available before first unlock or through unsuitable sync paths.', 'Use a ThisDeviceOnly accessibility class and verify migration without data loss.', 'backlog', true),
  task('CRY-02', 'Strengthen backup password derivation', 'High', 'Crypto', 'Password-protected backups need a modern, parameterized KDF and authenticated encryption.', 'Use Argon2id or a reviewed platform equivalent with per-backup salt, versioned parameters, and AEAD.', 'backlog', true),
  task('STO-02', 'Encrypt sensitive metadata', 'High', 'Storage', 'Some descriptive card fields remain outside the encrypted payload.', 'Classify fields and move all sensitive metadata into an authenticated encrypted record.', 'backlog', true),
  task('STO-03', 'Encrypt background and card images', 'High', 'Storage', 'Image files can reveal account and branding information at rest.', 'Encrypt private images, keep them out of shared media, and wipe superseded files.', 'backlog', true),
  task('FIL-01', 'Adopt scoped-storage-safe file access', 'High', 'Storage', 'Legacy or broad file handling increases privacy exposure and Android compatibility risk.', 'Use app-private storage and Storage Access Framework grants with minimal, revocable scope.', 'backlog', true),
  task('AND-01', 'Disable cleartext Android traffic', 'High', 'Network', 'The Android app should explicitly reject unencrypted network requests.', 'Set usesCleartextTraffic=false and a restrictive network security configuration for release.', 'backlog', true),
  task('DATA-01', 'Expire decrypted in-memory caches', 'High', 'Data', 'Decrypted card values can remain cached after lock or account-state changes.', 'Clear all plaintext caches on lock/background/logout and store the minimum necessary lifetime.', 'backlog', true),
  task('PERF-07', 'Stop creating Futures during build', 'High', 'Performance', 'Some widgets start asynchronous work from build, causing repeated reads and unstable rebuild behavior.', 'Move work to providers/initState, memoize results, and keep build methods pure.', 'backlog', true),
  task('PERF-08', 'Decrypt only visible cards', 'High', 'Performance', 'Lists can decrypt more card records than the viewport needs.', 'Use lazy paging, keyed caches, and reveal only the fields needed for visible items.', 'backlog', true),
  task('REL-02', 'Install OCR trained data atomically', 'High', 'Reliability', 'An interrupted trained-data copy can leave an apparently installed but corrupt model.', 'Write to a temporary file, verify hash/size, fsync where practical, then rename atomically.', 'backlog', true),
  task('DEP-04', 'Create an upstream scanner strategy', 'High', 'Dependencies', 'A large locally modified scanner fork increases patch, security, and upgrade burden.', 'Inventory local deltas, upstream or isolate them, pin provenance, and define an upgrade cadence.', 'backlog', true),
  task('DEP-05', 'Review the LiteRT native dependency', 'High', 'Dependencies', 'The scanner stack includes a large native inference runtime with meaningful size and maintenance cost.', 'Confirm it is required, update to a supported release, or replace it with a lighter scoped implementation.', 'backlog', true),
  task('APK-08', 'Reduce the scanner footprint', 'High', 'APK Size', 'The scanner stack contributes roughly 15.5 MB compressed to the APK.', 'Measure scanner assets and native libraries, remove unused models/ABIs, and consider an optional dynamic feature.', 'backlog', true),

  task('MEM-01', 'Dispose all controllers and subscriptions', 'Medium', 'Memory', 'Long-lived controllers, streams, and listeners need a complete ownership audit.', 'Document ownership and add dispose/cancel paths for every controller, subscription, timer, and observer.'),
  task('MEM-02', 'Bound application caches', 'Medium', 'Memory', 'Several caches need explicit entry, byte, and lifetime limits.', 'Add LRU or TTL policies and clear sensitive entries on memory pressure and lock.'),
  task('OCR-02', 'Cancel stale OCR work', 'Medium', 'Performance', 'OCR results can arrive after navigation or after a newer scan supersedes them.', 'Use cancellation tokens or generation IDs and ignore results from obsolete requests.'),
  task('OCR-03', 'Move heavy OCR work off the UI isolate', 'Medium', 'Performance', 'Image preprocessing can create frame stalls when performed on the main isolate.', 'Profile each stage and move CPU-heavy decoding/transforms to native code or isolates.'),
  task('PRV-03', 'Redact sensitive accessibility text', 'Medium', 'Privacy', 'Semantics labels can expose full card values to accessibility services.', 'Use non-sensitive labels by default and reveal values only after authenticated user intent.'),
  task('APK-05', 'Convert oversized raster branding assets', 'Medium', 'APK Size', 'Brand PNGs account for about 6.8 MB compressed and include inefficient formats/sizes.', 'Resize to actual display bounds and convert suitable art to WebP or vectors.'),
  task('APK-06', 'Remove duplicate and unused assets', 'Medium', 'APK Size', 'The asset tree contains likely duplicates and variants that may no longer be referenced.', 'Generate a reference manifest, visually verify candidates, then delete in small tested batches.'),
  task('APK-07', 'Subset bundled fonts', 'Medium', 'APK Size', 'Bundled font families may include glyphs and weights the app never renders.', 'Keep only used weights and generate Unicode-subset font files for supported locales.'),
  task('APK-09', 'Measure deferred scanner delivery', 'Medium', 'APK Size', 'Users who never scan cards still download the scanner stack.', 'Prototype Play Feature Delivery or a downloadable scan module and compare UX and size savings.'),
  task('APK-10', 'Publish an Android App Bundle', 'Medium', 'APK Size', 'Direct APK distribution cannot use all Play Store device targeting optimizations.', 'Use flutter build appbundle for store delivery and track per-device download size.'),
  task('BLD-04', 'Add release-size budgets', 'Medium', 'Build', 'APK growth is not automatically blocked or explained in CI.', 'Record per-ABI and component sizes, set budgets, and fail regressions above an agreed threshold.'),
  task('IOS-03', 'Add iOS privacy manifest coverage', 'Medium', 'Platform', 'Native APIs and third-party SDKs need reviewed privacy-reason declarations.', 'Audit required-reason APIs and ship a complete PrivacyInfo.xcprivacy.'),
  task('IOS-04', 'Verify iOS backup exclusions', 'Medium', 'Storage', 'Generated caches and recoverable sensitive files may be included in device backups.', 'Classify files and set backup exclusion flags where restoration is unnecessary or unsafe.'),
  task('AND-02', 'Minimize Android permissions', 'Medium', 'Security', 'Manifest permissions should be justified against current features and Android versions.', 'Remove obsolete permissions and document the user-facing reason for each retained permission.'),
  task('REL-03', 'Make migrations crash-safe', 'Medium', 'Reliability', 'Storage and schema migrations need restart-safe checkpoints.', 'Use idempotent steps, versioned state, backups, and tests for interruption at every phase.'),
  task('FIL-02', 'Centralize file lifecycle management', 'Medium', 'Storage', 'Image and export files are created and deleted through multiple paths.', 'Introduce one file repository with ownership, cleanup, and orphan reconciliation.'),
  task('FIL-03', 'Use safe temporary files', 'Medium', 'Storage', 'Temporary exports and camera artifacts need reliable cleanup.', 'Use app-private temporary directories, random names, restrictive permissions, and finally-block deletion.'),
  task('MED-01', 'Normalize and resize media once', 'Medium', 'Performance', 'The same source image can be transformed repeatedly across screens.', 'Create canonical display and thumbnail derivatives at import time.'),
  task('MED-02', 'Strip image metadata', 'Medium', 'Privacy', 'Imported photos may retain EXIF location and device metadata.', 'Remove nonessential metadata before storing, sharing, or backing up images.'),
  task('STO-01', 'Define a storage data map', 'Medium', 'Storage', 'Sensitive values are spread across preferences, databases, files, and caches.', 'Document every field, location, encryption state, lifetime, and deletion path.'),
  task('REL-01', 'Standardize recoverable failures', 'Medium', 'Reliability', 'Service errors are handled inconsistently across the UI.', 'Adopt typed failures, user-safe messages, retry policy, and structured diagnostics.'),
  task('CLN-01', 'Remove dead Dart code', 'Medium', 'Cleanup', 'Legacy widgets, services, and helper branches increase maintenance cost.', 'Use analyzer/reference evidence and focused tests before deleting candidates.'),
  task('CLN-02', 'Prune unused native scanner code', 'Medium', 'Cleanup', 'The local Android scanner fork carries code paths the app may not call.', 'Trace entry points and R8 output, then remove unused activities, resources, and models safely.'),
  task('CLN-03', 'Clean obsolete project artifacts', 'Medium', 'Cleanup', 'Generated, archived, and historical files can drift into the repository or packages.', 'Create an allowlist for source assets and exclude generated reports, captures, and scratch files.'),
  task('REF-01', 'Split oversized screens', 'Medium', 'Refactoring', 'Large screen files mix orchestration, state, persistence, and presentation.', 'Extract feature controllers and small focused widgets with explicit inputs.'),
  task('REF-02', 'Separate domain and persistence models', 'Medium', 'Refactoring', 'Storage details leak into business and UI logic.', 'Introduce domain entities plus repository mapping boundaries.'),
  task('REF-03', 'Consolidate card formatting', 'Medium', 'Refactoring', 'Masking and display formatting are repeated in multiple widgets.', 'Create tested value objects and formatters for PAN, expiry, CVV labels, and names.'),
  task('REF-04', 'Centralize route protection', 'Medium', 'Refactoring', 'Screens make local decisions about access and lock state.', 'Use guarded navigation and a shared protected-route policy.'),
  task('REF-05', 'Reduce provider coupling', 'Medium', 'Refactoring', 'Broad provider reads cause hidden dependencies and unnecessary rebuilds.', 'Expose narrow selectors and inject feature-specific interfaces.'),
  task('REF-06', 'Create a card image repository', 'Medium', 'Refactoring', 'Image lookup, decode, cache, and deletion logic is duplicated.', 'Put those responsibilities behind one testable repository.'),
  task('REF-07', 'Adopt typed platform channels', 'Medium', 'Refactoring', 'Stringly typed method-channel contracts are easy to break silently.', 'Use Pigeon or strongly typed wrappers with versioned error contracts.'),
  task('REF-08', 'Remove magic configuration values', 'Medium', 'Refactoring', 'Timeouts, image limits, and layout constants are scattered.', 'Collect reviewed constants by feature and document their rationale.'),
  task('PERF-01', 'Add frame and startup benchmarks', 'Medium', 'Performance', 'Performance changes cannot be compared without repeatable baselines.', 'Track cold start, first useful frame, transitions, and long-frame counts on representative devices.'),
  task('PERF-02', 'Use selective provider rebuilds', 'Medium', 'Performance', 'Wide watches rebuild large portions of the home screen.', 'Use selectors and split consumers around the smallest changing regions.'),
  task('PERF-03', 'Precompute expensive derived values', 'Medium', 'Performance', 'Sorting, filtering, and display transformations repeat during rebuilds.', 'Memoize derived lists and recompute only when source inputs change.'),
  task('PERF-04', 'Paginate large card collections', 'Medium', 'Performance', 'The current design will scale poorly when many cards and images are loaded.', 'Use lazy builders, incremental queries, and bounded prefetching.'),
  task('PERF-05', 'Move crypto batches off the UI isolate', 'Medium', 'Performance', 'Bulk encryption and decryption may block frames.', 'Batch work and use native/background execution after profiling the actual bottleneck.'),
  task('PERF-06', 'Reduce animation repaint area', 'Medium', 'Performance', 'Card transitions repaint more of the screen than necessary.', 'Add repaint boundaries, isolate transforms, and profile raster time in release mode.'),
  task('TST-01', 'Add authentication lifecycle tests', 'Medium', 'Testing', 'Critical lock and resume behavior lacks complete automated coverage.', 'Test cold start, timeout, background, biometric cancel, and route interception.'),
  task('TST-02', 'Add malicious backup corpus tests', 'Medium', 'Testing', 'Import security needs adversarial archives, not only happy-path files.', 'Cover traversal, zip bombs, duplicates, invalid JSON, huge dimensions, and interrupted commits.'),
  task('TST-03', 'Add native Android scanner tests', 'Medium', 'Testing', 'The native scanner module currently has no meaningful automated tests.', 'Test bitmap limits, lifecycle cleanup, result mapping, cancellation, and corrupted inputs.'),
  task('TST-04', 'Add golden tests for card rendering', 'Medium', 'Testing', 'Visual regressions in masking and transitions are difficult to catch.', 'Add representative card golden tests across themes, text scales, and aspect ratios.'),
  task('TST-05', 'Raise meaningful coverage above 44.1%', 'Medium', 'Testing', 'Current coverage leaves security and persistence paths under-tested.', 'Prioritize risk-weighted coverage targets instead of a repository-wide vanity percentage.'),
  task('TST-06', 'Test migrations and rollback', 'Medium', 'Testing', 'Data upgrades need proof against interruption and old-version fixtures.', 'Create versioned fixtures and fault-injection tests for every migration step.'),
  task('TST-07', 'Add memory regression tests', 'Medium', 'Testing', 'Repeated scan/open/close flows can regress without a measured ceiling.', 'Automate repeated journeys and record native, Dart heap, and image memory plateaus.'),
  task('TST-08', 'Add accessibility checks', 'Medium', 'Testing', 'Focus order, semantics, text scaling, and contrast need regression coverage.', 'Add widget checks and manual device scenarios for protected-value interactions.'),
  task('DEP-01', 'Remove unused Dart packages', 'Medium', 'Dependencies', 'Declared packages increase update and attack-surface burden even when lightly used.', 'Map imports to pubspec entries, remove unused direct dependencies, then rebuild all platforms.'),
  task('DEP-02', 'Pin and monitor dependency updates', 'Medium', 'Dependencies', 'Security and compatibility updates need a predictable process.', 'Use lockfile review, automated update PRs, changelog checks, and scheduled upgrade windows.'),
  task('DEP-03', 'Generate a software bill of materials', 'Medium', 'Dependencies', 'Native and Dart transitive components are not summarized in one auditable artifact.', 'Generate an SBOM per release and retain licenses, versions, and provenance.'),
  task('BLD-01', 'Make release hardening explicit', 'Medium', 'Build', 'Release flags and platform protections should be reviewable rather than implicit.', 'Document and test obfuscation, symbol handling, shrinking, signing, and environment configuration.'),
  task('BLD-02', 'Separate environment configuration', 'Medium', 'Build', 'Build-time values risk accidental production/development mixing.', 'Use typed flavors with validated required settings and no secrets in source.'),
  task('BLD-03', 'Reproduce release builds in CI', 'Medium', 'Build', 'Local-only release generation weakens traceability.', 'Pin toolchains, build signed artifacts in CI, and publish checksums plus size reports.'),
  task('CI-01', 'Create a security and quality gate', 'Medium', 'CI/CD', 'Analysis, tests, secret scanning, dependency review, and size checks are not one enforced gate.', 'Run all checks on every merge and require them before release branches can advance.'),
  task('ERR-01', 'Redact production diagnostics', 'Medium', 'Security', 'Errors may include card identifiers, file paths, or OCR fragments.', 'Adopt structured logging with a field allowlist and verify release logs using seeded sensitive data.'),
  task('A11Y-01', 'Improve keyboard and screen-reader operation', 'Medium', 'Accessibility', 'Interactive card controls need consistent focus, labels, and large-text behavior.', 'Audit semantics, focus order, tap targets, contrast, and 200% text scaling.'),
  task('DOC-01', 'Document the security architecture', 'Medium', 'Documentation', 'Future changes need a clear model of trust boundaries and sensitive-data flows.', 'Maintain a threat model, crypto/storage decisions, backup format, and incident response notes.'),
  task('OPS-01', 'Define a vulnerability response process', 'Medium', 'Operations', 'Dependency and security findings need ownership and remediation timelines.', 'Assign owners, severity SLAs, disclosure contacts, and an emergency release path.'),

  task('APK-01', 'Enable release code shrinking', 'Medium', 'APK Size', 'Release shrinking was enabled and verified.', 'Keep the configuration covered by release smoke tests.', 'done'),
  task('APK-02', 'Enable resource shrinking', 'Medium', 'APK Size', 'Unused Android resources are removed from release artifacts.', 'Monitor the resource report after major plugin updates.', 'done'),
  task('APK-03', 'Split APKs by ABI', 'Medium', 'APK Size', 'Per-ABI artifacts are now produced for direct distribution.', 'Keep universal APKs out of the normal release channel.', 'done'),
  task('APK-04', 'Remove obsolete packaged assets', 'Medium', 'APK Size', 'An initial set of unused assets was safely removed.', 'Continue pruning only with reference and visual verification.', 'done'),
  task('UI-01', 'Fix yellow card-transition artifacts', 'Medium', 'UI', 'The transient yellow lines visible during card open/close were corrected.', 'Retain a release-mode visual regression scenario for the transition.', 'done'),
];

export const statusLabels: Record<TaskStatus, string> = {
  backlog: 'Backlog',
  picked: 'Picked',
  'in-progress': 'In progress',
  blocked: 'Blocked',
  done: 'Complete',
  skipped: 'Skipped',
};

export const statusOrder: TaskStatus[] = ['backlog', 'picked', 'in-progress', 'blocked', 'done', 'skipped'];
