org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
kotlin.jvmTarget=17
org.gradle.java.home=/opt/homebrew/opt/openjdk@25/libexec/openjdk.jdk/Contents/Home
android.experimental.disableCompileSdkChecks=true
android.experimental.disableResourceOptimization=true
android.nonTransitiveRClass=false
android.uniquePackageNames=false
android.newDsl=false
android.builtInKotlin=false
